services:
  manager:
    build: .
    image: v2config-manager:latest
    container_name: v2mgr
    entrypoint: ["/usr/local/bin/v2mgr"] 
    
    command: ["/config.yaml"]  
    
    volumes:
      - ./config.yaml:/config.yaml:ro
      - ./data:/data
      - ./snapshots:/snapshots
      - ./output:/output
    ports:
      - "8080:8080"
    restart: unless-stopped

  agent1:
    image: v2config-manager:latest
    container_name: v2agent1
    entrypoint: ["/usr/local/bin/v2agent"] # باینری agent
    command: [] 
    ports:
      - "8081:8081"
    restart: unless-stopped
    depends_on:
      - manager
