name: Go CI

on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'
          cache: true

      - name: Go mod tidy
        run: go mod tidy

      - name: Build
        run: |
          go build ./cmd/manager
          go build ./cmd/agent

      - name: Unit Tests
        run: go test -v ./...

  docker:
    runs-on: ubuntu-latest
    needs: build
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Prepare config and dirs
        run: |
          cp -f config.example.yaml config.yaml
          mkdir -p output data snapshots

      # Compose via official action (no apt, no plugin install)
      - name: Compose up (build + start)
        uses: docker/compose-action@v3
        with:
          compose-file: ./docker-compose.yml
          up: -d --build

      - name: Wait for health
        shell: bash
        run: |
          set -euo pipefail
          tries=0
          until curl -fsS http://localhost:8080/healthz >/dev/null; do
            tries=$((tries+1))
            if [ $tries -gt 40 ]; then
              echo "Timed out waiting for service health"
              docker ps || true
              # container_name in docker-compose.yml: v2mgr
              docker logs v2mgr || true
              exit 1
            fi
            sleep 2
          done
          echo "Service healthy ✔"

      - name: Dump container logs (always)
        if: always()
        run: |
          docker ps
          docker logs v2mgr || true

      - name: Compose down (always)
        if: always()
        uses: docker/compose-action@v3
        with:
          compose-file: ./docker-compose.yml
          down: -v