name: Go CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'
          cache: true
      - name: Go mod tidy
        run: go mod tidy
      - name: Build
        run: |
          go build ./cmd/manager
          go build ./cmd/agent
      - name: Unit Tests
        run: go test -v ./...

  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install Docker Compose v2 plugin
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose-plugin
          docker compose version

      - name: Build Docker image
        run: docker build -t v2config-manager:ci .

      - name: Smoke test with Docker Compose
        run: |
          set -e
          cp config.example.yaml config.yaml
          mkdir -p output data snapshots
          docker compose up -d --build

          echo "Waiting for health endpoint..."
          tries=0
          until curl -fsS http://localhost:8080/healthz >/dev/null; do
            tries=$((tries+1))
            if [ $tries -gt 40 ]; then
              echo "Timed out waiting for service health"
              docker compose ps || true
              docker compose logs --no-color || true
              exit 1
            fi
            sleep 2
          done
          echo "Service healthy ✔"
          docker compose down -v
